# -*- coding: utf-8 -*-

from PyQt6 import QtCore, QtGui, QtWidgets


class UiQuestionwindow(object):
    def setupUi(self, QuestionWindow):
        QuestionWindow.setObjectName("QuestionWindow")
        QuestionWindow.resize(710, 560)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(QuestionWindow.sizePolicy().hasHeightForWidth())
        QuestionWindow.setSizePolicy(sizePolicy)
        QuestionWindow.setMinimumSize(QtCore.QSize(710, 560))
        QuestionWindow.setMaximumSize(QtCore.QSize(710, 560))
        self.question_text = QtWidgets.QLabel(QuestionWindow)
        self.question_text.setGeometry(QtCore.QRect(0, 60, 711, 201))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.question_text.setFont(font)
        self.question_text.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.question_text.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.question_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.question_text.setObjectName("question_text")
        self.current_num = QtWidgets.QLCDNumber(QuestionWindow)
        self.current_num.setGeometry(QtCore.QRect(250, 480, 81, 41))
        self.current_num.setSmallDecimalPoint(False)
        self.current_num.setDigitCount(2)
        self.current_num.setSegmentStyle(QtWidgets.QLCDNumber.SegmentStyle.Flat)
        self.current_num.setProperty("value", 0.0)
        self.current_num.setObjectName("current_num")
        self.proceed_bt = QtWidgets.QPushButton(QuestionWindow)
        self.proceed_bt.setGeometry(QtCore.QRect(510, 460, 191, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.proceed_bt.setFont(font)
        self.proceed_bt.setObjectName("proceed_bt")
        self.back_bt = QtWidgets.QPushButton(QuestionWindow)
        self.back_bt.setGeometry(QtCore.QRect(10, 460, 191, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.back_bt.setFont(font)
        self.back_bt.setObjectName("back_bt")
        self.change_lang_bt = QtWidgets.QPushButton(QuestionWindow)
        self.change_lang_bt.setGeometry(QtCore.QRect(510, 10, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.change_lang_bt.setFont(font)
        self.change_lang_bt.setObjectName("change_lang_bt")
        self.horizontalLayoutWidget = QtWidgets.QWidget(QuestionWindow)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 270, 701, 82))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rB1 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rB1.sizePolicy().hasHeightForWidth())
        self.rB1.setSizePolicy(sizePolicy)
        self.rB1.setMinimumSize(QtCore.QSize(60, 80))
        self.rB1.setMaximumSize(QtCore.QSize(60, 80))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.rB1.setFont(font)
        self.rB1.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.rB1.setIconSize(QtCore.QSize(20, 20))
        self.rB1.setObjectName("rB1")
        self.horizontalLayout.addWidget(self.rB1)
        self.rB2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rB2.sizePolicy().hasHeightForWidth())
        self.rB2.setSizePolicy(sizePolicy)
        self.rB2.setMinimumSize(QtCore.QSize(120, 80))
        self.rB2.setMaximumSize(QtCore.QSize(120, 80))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.rB2.setFont(font)
        self.rB2.setObjectName("rB2")
        self.horizontalLayout.addWidget(self.rB2)
        self.rB3 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rB3.sizePolicy().hasHeightForWidth())
        self.rB3.setSizePolicy(sizePolicy)
        self.rB3.setMinimumSize(QtCore.QSize(100, 80))
        self.rB3.setMaximumSize(QtCore.QSize(100, 80))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.rB3.setFont(font)
        self.rB3.setObjectName("rB3")
        self.horizontalLayout.addWidget(self.rB3)
        self.rB4 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rB4.sizePolicy().hasHeightForWidth())
        self.rB4.setSizePolicy(sizePolicy)
        self.rB4.setMinimumSize(QtCore.QSize(50, 80))
        self.rB4.setMaximumSize(QtCore.QSize(50, 80))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.rB4.setFont(font)
        self.rB4.setCheckable(True)
        self.rB4.setObjectName("rB4")
        self.horizontalLayout.addWidget(self.rB4)
        self.num_of_questions = QtWidgets.QLCDNumber(QuestionWindow)
        self.num_of_questions.setGeometry(QtCore.QRect(380, 480, 81, 41))
        self.num_of_questions.setDigitCount(2)
        self.num_of_questions.setObjectName("num_of_questions")
        self.slash = QtWidgets.QLabel(QuestionWindow)
        self.slash.setGeometry(QtCore.QRect(340, 450, 81, 101))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(48)
        self.slash.setFont(font)
        self.slash.setObjectName("slash")

        self.retranslateUi(QuestionWindow)
        QtCore.QMetaObject.connectSlotsByName(QuestionWindow)

    def retranslateUi(self, QuestionWindow):
        _translate = QtCore.QCoreApplication.translate
        QuestionWindow.setWindowTitle(_translate("QuestionWindow", "Myers-Briggs test"))
        self.question_text.setText(_translate("QuestionWindow", "ТЕКСТ ВОПРОСА"))
        self.proceed_bt.setText(_translate("QuestionWindow", "Далее"))
        self.back_bt.setText(_translate("QuestionWindow", "Назад"))
        self.change_lang_bt.setText(_translate("QuestionWindow", "Сменить язык"))
        self.rB1.setText(_translate("QuestionWindow", "Нет"))
        self.rB2.setText(_translate("QuestionWindow", "Скорее нет"))
        self.rB3.setText(_translate("QuestionWindow", "Скорее да"))
        self.rB4.setText(_translate("QuestionWindow", "Да"))
        self.slash.setText(_translate("QuestionWindow", "/"))
